@file:Suppress("unused")

package com.github.gkdrateit.permission

enum class Permission {
    COURSE_CREATE, COURSE_READ, COURSE_UPDATE, COURSE_DELETE,
    REVIEW_CREATE, REVIEW_READ, REVIEW_UPDATE, REVIEW_DELETE,
    TEACHER_CREATE, TEACHER_READ, TEACHER_UPDATE, TEACHER_DELETE,
    USER_CREATE, USER_READ, USER_UPDATE, USER_DELETE,
}