# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Manual

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Parse Version
        run: |
          echo ${{ env.GITHUB_WORKSPACE }}
          echo "BUILD_VER=$(cat ${{ env.GITHUB_WORKSPACE }}/build.gradle.kts | grep "version = " | sed -E "s/(version| |=|\")//g")" >> $GITHUB_ENV
          echo ${{ env.BUILD_VER }}
          [[ ${{ env.BUILD_VER }} == "" ]] || exit 1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build -x test
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ${{ env.GITHUB_WORKSPACE }}
          build-args: BUILD_VER=${{ env.BUILD_VER }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/back:${{ env.BUILD_VER }}
